# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.runs/synth_5/.Xil/Vivado-6004-LAPTOP-ZMX/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter areaStrategy 2
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new
    d:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/ip/clk_50M
    d:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/ip/instruction_mem
  } D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new
    d:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/ip/clk_50M
    d:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/ip/instruction_mem
  } {
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.runs/synth_5/.Xil/Vivado-6004-LAPTOP-ZMX/realtime/instruction_mem_stub.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.runs/synth_5/.Xil/Vivado-6004-LAPTOP-ZMX/realtime/clk_50M_stub.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ALU.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ALU_mux.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/CPU.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ControlUnit.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/DataMem.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/EX_ME.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/Forward_Unit.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/Hazard_Unit.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ID_EX.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/IF_ID.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ImmGen.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/InsMem.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/LightShow.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/ME_WB.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/PC.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/PC_mux.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/RF_mux.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/RegFile.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/rs232.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/sr1_mux.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/sr2_mux.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/uart_rx.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/uart_tx.v
      D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.srcs/sources_1/new/top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/桌面/本科课程/计算机组成与体系结构/计组小学期/pipelined_CPU/Pipelined_CPU_RISCV/pipeline_cpu_riscv.runs/synth_5/.Xil/Vivado-6004-LAPTOP-ZMX/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
