webtalk_init -webtalk_dir D:/GitRepo/pipelined_CPU/IC_UART/IC_UART.sim/sim_1/behav/xsim/xsim.dir/tb_rs232_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 25 20:57:08 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d5481103-3b6f-4d04-a2aa-662e5e017598" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "576a5b2bdb524d3c829ed52025bd7595" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2895 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1751796732 -regid "" -xml D:/GitRepo/pipelined_CPU/IC_UART/IC_UART.sim/sim_1/behav/xsim/xsim.dir/tb_rs232_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/GitRepo/pipelined_CPU/IC_UART/IC_UART.sim/sim_1/behav/xsim/xsim.dir/tb_rs232_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/GitRepo/pipelined_CPU/IC_UART/IC_UART.sim/sim_1/behav/xsim/xsim.dir/tb_rs232_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
