# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/control.xdc

# IP: ip/ila_data/ila_data.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_data || ORIG_REF_NAME==ila_data} -quiet] -quiet
